#! /bin/sh

sxhkd &

bspc config border_width         2
bspc config window_gap          26
bspc config top_padding		27

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d code web misc

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Firefox desktop=^2 follow=on

~/.fehbg
#xsetroot -solid white

compton -cCf -D 5 -i 0.9 -r 8 -t -11 -l -11 -b

$HOME/.config/polybar/launch.sh
